### PR TITLE
Support cordova-android@7

### PR DESCRIPTION
**Pull request by davidgovea**
@podtrackers - thanks for cleaning up the upstream repo! Been using your fork for a while.

The `AndroidManifest.xml` file has changed locations in `cordova-android@7`.

This PR adds support for the new file location, while maintaining support for older versions, too. Let me know what you think -- thanks!

---
**Note:** unfortunately, my branch can't be pulled as-is into a project, because the new cordova plugin spec checker is so strict that the mismatch between git url and the `repository` field in `package.json` cause cordova to reject the plugin.. I have a separate `thrash` branch that I'm using until this PR is merged -- the only differences are the github links in the package. What a pain!

### CODE REVIEW

**Comment by salim7** [comment]
Can someone merge this PR or is this project dead?

**Comment by davidgovea** [comment]
ping @podtrackers - would be happy to help maintain this repo if you're availability is limited.

**Comment by podtrackers** [comment]
Hi,

The guy that forked this repo has left and I’m not sure we even use it anymore…

I’ll merge you PR when I get a sec, sorry!

Mark,
Pod Techie,
mark@podtrackers.com <mailto:mark@podtrackers.com>
0424561313

**Comment by davidgovea** [comment]
Hey Mark @podtrackers - thanks for merging!

The last step needed here is to tag the release and publish `0.2.0` to npm. Looks like `tech@podtrackers.com` is listed in the npm maintainers, in addition to Chris.

Hopefully you're all set up for a quick `npm publish`. And again, I'd be happy to help with the repo/npm responsibilities.

Thanks!
-- David `<govea.d@gmail.com>`

**Pull request merged**
